#!/bin/bash
#
# File: bootstrap-ruby
#
# Called from Dockerfile
#
# Install rbenv and needed ruby versions.
# based on https://gist.github.com/mhutter/1682948
set -e

RBVER=$(cat .ruby-version)
PROFILE=~/.bashrc

apt-get update
apt-get install -y \
  build-essential zlib1g-dev \
  libssl-dev openssl \
  libreadline-dev \
  sqlite3 libsqlite3-dev \
  libxslt-dev libxml2-dev \
  curl wget git-core

git clone https://github.com/sstephenson/rbenv.git ~/.rbenv

echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> $PROFILE
echo 'eval "$(rbenv init -)"' >> $PROFILE
mkdir -p ~/.rbenv/plugins
source $PROFILE

git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
rbenv install $RBVER
rbenv rehash
rbenv global $RBVER
gem install bundler
rbenv rehash
